// <auto-generated />
using System;
using LearnU_WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearnU_WebApi.Migrations
{
    [DbContext(typeof(LearnUContext))]
    partial class LearnUContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearnU_WebApi.Models.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.SocialMedia", b =>
                {
                    b.Property<Guid>("SocialMediaId")
                        .HasColumnName("SocialMediaID");

                    b.Property<string>("SocialMediaName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("SocialMediaId");

                    b.ToTable("SocialMedia");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.UserMedia", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("UserID");

                    b.Property<Guid>("SocialMediaId")
                        .HasColumnName("SocialMediaID");

                    b.HasKey("UserId", "SocialMediaId");

                    b.HasIndex("SocialMediaId");

                    b.ToTable("UserMedia");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("UserID");

                    b.Property<string>("Extract")
                        .HasMaxLength(400)
                        .IsUnicode(false);

                    b.Property<string>("Language")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("UserId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("UserID");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.Property<byte[]>("Password")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("RegistryDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("RoleId")
                        .HasColumnName("RoleID");

                    b.Property<string>("SecondLastName")
                        .HasColumnName("SecondLAstName")
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.UserMedia", b =>
                {
                    b.HasOne("LearnU_WebApi.Models.SocialMedia", "SocialMedia")
                        .WithMany("UserMedia")
                        .HasForeignKey("SocialMediaId")
                        .HasConstraintName("FK_UserMedia_SocialMedia");

                    b.HasOne("LearnU_WebApi.Models.Users", "User")
                        .WithMany("UserMedia")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserMedia_Users");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.UserProfile", b =>
                {
                    b.HasOne("LearnU_WebApi.Models.Users", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("LearnU_WebApi.Models.UserProfile", "UserId")
                        .HasConstraintName("FK_UserProfile_Users");
                });

            modelBuilder.Entity("LearnU_WebApi.Models.Users", b =>
                {
                    b.HasOne("LearnU_WebApi.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
